### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by pschuchmann** [ed3/ckeditor_fa#1]
Hi there,

i got some issues, when using your plugin.

I added the `ckeditorfa5` to the `extraPlugins ` and additionally had to add it to the `toolbar`, then it showed up. The `contentsCss` is configured as well.

Now I can see all icons, but when I search for `chevron`, the icons won't come up in the result. And I don't know how to add the icon to my content. Clicking on the icon or ok won't pass it to the editor.

Any help on that? 

Anyways, thank you for developing this addon!

**Comment by ed3** [comment]
Hi,

If you want to find an icon (chevron) just write in the last text input of first line; in the last text input of second line appear just the clicked item value.

Good Luck!

**Comment by pschuchmann** [comment]
This works as intended. But the insert of the icon into the editor area needs specific options set in the profile. 

`CKEDITOR.dtd.$removeEmpty['span'] = false;

This needs to be set, otherwise the icon is removed.

**Comment by ed3** [comment]
Thanks for info.
in config.js set:
`config.allowedContent = true;`
