### ISSUE TITLE
Uncaught TypeError: getElementsByTagName

### ISSUE THREAD

**Issue by innats** [ed3/ckeditor_fa#11]
Hi Ed3,

Thanks for a cool plugin! Unfortunately, I experience some issues with it and hoping you know how to help it. :)

The plugin is displayed correctly, but it won't allow me to select icons. I get a following error:

ckeditorfa.js?t=L7C8:3 Uncaught TypeError: Cannot read properties of undefined (reading 'getElementsByTagName')
    at klick (ckeditorfa.js?t=L7C8:3)
    at HTMLAnchorElement.onclick (VM211 test.php:1)
klick @ ckeditorfa.js?t=L7C8:3
onclick @ test.php:1

I've tried to rename plugin to ckeditorfa from ckeditorfa5, which didn't help.

**Comment by ed3** [comment]
Hi,
I fixed, keep folder name ckeditorfa.
