### ISSUE TITLE
Error icons partialy showing

### ISSUE THREAD

**Issue by seyfcom** [ed3/ckeditor_fa#12]
I use the ckeditorfa plugin for fontawsome 6 pro in a Symfony 5.4 project, with webpack and only some icons are showing in the plugin... Brands icones are there, no regular icon, just small squares and some few Solid icons are visible, the rest is smal squares too.

If I insert a icon, then it works, my system knows them, in the ckeditor text zone, I seen them, just NOT in the "fontawsome chooser" plugin... 

Any ideas why it is like this?

php.7.4
symfony 5.4.4
fontawesome-pro: 6.1.0

**Comment by ed3** [comment]
ckeditorfa work for moment only with FontAwesome 6 free (not pro)!

**Comment by seyfcom** [comment]
oh! that's sad!
Can you edit readme to inform people, would be very nice.

Can I help in someways to make it happen? Do you have the 6Pro? If not, do you want a seat and be able to test it? Can I code a part of something?

**Comment by seyfcom** [comment]
CLOSING UNTIL FURTHER NOTICE
