### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by egrefin** [ed3/ckeditor_fa#2]
For accessibility, I added one line for onOk:function () in ckeditorfa.js:
icon.setAttribute('aria-hidden', 'true');
As mentionned here: https://fontawesome.com/how-to-use/on-the-web/other-topics/accessibility

It would be cool if the aria-hidden attribute is included in the next update ;)
Thanks

**Comment by ed3** [comment]
Thank you @egrefin !
