### ISSUE TITLE
CSS .fa definition problem

### ISSUE THREAD

**Issue by egrefin** [ed3/ckeditor_fa#3]
The class .fa is defined in a global context, not in a specific Id or class.
This affects all .fa classes used in the same html page!
So, to constrain your .fa definition without to affect all the page, I modified your css file in adding '.cke_dialog_ui_vbox_child a span' before .fa.

.cke_dialog_ui_vbox_child a span.fa {display:inline-block;font:normal normal normal 14px/1 FontAwesome;font-size:inherit;text-rendering:auto;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;color:inherit;cursor:pointer}

.cke_dialog_ui_vbox_child a span.fa:before {color:inherit}

Hope you will modify this in a next upgrade of your plugin ;)

**Comment by ed3** [comment]
I changed the style, but I didn't notice any difference. I deleted the color function to keep the original color of the icons in the ckeditor dialog. If you didn't get what you wanted then give me more explanations.
