### ISSUE TITLE
When using ckeditor and ckeditorfa5 in 2 inputs

### ISSUE THREAD

**Issue by DAGpro** [ed3/ckeditor_fa#6]
When using ckeditor and ckeditorfa5 in 2 inputs, if the plugin was used in one of them, then in the second it is no longer possible to select an icon from the list.

Windows 10
ckeditor 4.14
ckeditorfa version from March 25, 2020
Google Chrome 80

**Comment by ed3** [comment]
In the last input text intentionally I left it so that no wrong value was entered (has the role of visualization only).
